version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: cd project/flask && docker build -t pyflask:latest -f flask/Dockerfile .

  lsdir:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: pwd
      - run: ls -lah ~
      - run: ls -lah
      - run: ls -lah ..

workflows:
  allinall:
    jobs:
      - build
      - lsdir
