version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run: docker build -t pyflask:latest -f flask/Dockerfile .

  lsdir:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run: cat flask/Dockerfile

workflows:
  allinall:
    jobs:
      - build
      - lsdir
